version: "3.1"

services:
  api3:
    image: api3
    ports:
      - 3500:3500
  db:
    ports:
      - 3306:3306
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
